apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-cicd-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-cicd-bot
  template:
    metadata:
      labels:
        app: smart-cicd-bot
    spec:
      containers:
        - name: smart-cicd-bot
          image: smart-cicd-bot:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: smart-cicd-bot-service
spec:
  selector:
    app: smart-cicd-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
